---
title: "project2_nn_classification"
author: "EMVP"
date: "2023-05-01"
output: word_document
---
```{r}
#Q1
if (!requireNamespace("tidyverse")) install.packages('tidyverse')
if (!requireNamespace("caret")) install.packages('caret')
if (!requireNamespace("neuralnet")) install.packages('neuralnet')
if (!requireNamespace("keras")) install.packages('keras')
if (!requireNamespace("e1071")) install.packages('e1071')

library(tidyverse)
library(caret)
library(neuralnet)
library(keras)
library(e1071)

#load data
data <- read.csv('/Users/mustafayigitisik/Desktop/stuff/semesters/spring 2023/ams 580/project2/Titanic.csv')
#exclude unnecessary 4 columns and empty values in age column 
data <- subset(data, select = -c(PassengerId,Name,Ticket,Cabin))
data <- subset(data, is.na(Age) == FALSE)

data$Embarked[data$Embarked == ""] = NA
data <- subset(data, is.na(Embarked) == FALSE)
data <- model.matrix(~., data = data)[,-1]
data <- data.frame(data)
dim(data)[1]
# 712 passengers are left after this step

set.seed(123)
training.samples <- data$Survived %>% createDataPartition(p = 0.75, list = FALSE)
train.data <- data[training.samples, ]
test.data <- data[-training.samples, ]
str(train.data) # 534 obs
str(test.data) # 178 obs
```

```{r}
#Q2
set.seed(123)
model = neuralnet(Survived~., data = train.data, hidden = 0, err.fct = "sse", linear.output = F)
plot(model, rep = "best")

probabilities = predict(model, test.data)
predicted.classes = ifelse(probabilities > 0.5, 1, 0)

confusionMatrix(factor(predicted.classes), factor(test.data$Survived), positive = "1")
```

```{r}
#Q3
set.seed(123)
model = neuralnet(Survived~., data = train.data, hidden = 0, err.fct = "ce", linear.output = F)
plot(model, rep = "best")

probabilities = predict(model, test.data)
predicted.classes = ifelse(probabilities > 0.5, 1, 0)

confusionMatrix(factor(predicted.classes), factor(test.data$Survived), positive = "1")
```

```{r}
#Q4
set.seed(123)
model = glm(Survived~., family = binomial, data = train.data)

model

probabilities = model %>% predict(test.data, type = "response")
predicted.classes = ifelse(probabilities > 0.5, 1, 0)

confusionMatrix(factor(predicted.classes), factor(test.data$Survived), positive = "1")
```

```{r}
#Q5
set.seed(123)
model = neuralnet(Survived~., data = train.data, hidden = 3, err.fct = "sse", linear.output = F)
plot(model, rep = "best")

probabilities = predict(model, test.data)
predicted.classes = ifelse(probabilities > 0.5, 1, 0)

confusionMatrix(factor(predicted.classes), factor(test.data$Survived), positive = "1")
```

```{r}
#Q6
set.seed(123)
model = neuralnet(Survived~., data = train.data, hidden = 3, err.fct = "ce", linear.output = F)
plot(model, rep = "best")

probabilities = predict(model, test.data)
predicted.classes = ifelse(probabilities > 0.5, 1, 0)

confusionMatrix(factor(predicted.classes), factor(test.data$Survived), positive = "1")
```