---
title: "ams580_hw5"
author: "Mustafa Yigit Isik"
date: "2023-03-08"
output:
  word_document: default
  html_document:
    df_print: paged
---
#**Question 1**
```{r}
#Install Packs
if (!requireNamespace("tidyverse")) install.packages('tidyverse')
if (!requireNamespace("caret")) install.packages('caret')
if (!requireNamespace("randomForest")) install.packages('randomForest')
if (!requireNamespace("party")) install.packages('party')
library(tidyverse)
library(caret)
library(randomForest)
library(party)
```
```{r}
#Read/Clean Data
data <- read.csv('/Users/mustafayigitisik/Desktop/stuff/semesters/spring 2023/ams 580/hw5_rf_gini/Titanic1.csv')
#remove the instructed 3 columns
data <- subset(data, select = -c(Name, Ticket, Cabin))
#remove rows where age is empty 
data <- data[!(is.na(data$Age) | data$Age==""), ]
cat('There are', nrow(data), 'observations left.')
data$Survived <- as.factor(data$Survived)
data$Sex <- ifelse(data$Sex=="male",1,0)
str(data)
```
```{r}
#Split Data
set.seed(123)
training.samples <- data$Survived %>% 
  createDataPartition(p = 0.75, list = FALSE)
train.data  <- data[training.samples, ]
test.data <- data[-training.samples, ]
```
# Question 2
```{r}
set.seed(123)
model <- train(
  Survived ~., data = train.data, method = "rf",
  trControl = trainControl("cv", number = 10),
  importance = TRUE
  )
model$bestTune
```

```{r}
model$finalModel
```
```{r}
## Sensitivity
148/(148+70)
## Specificity
281/(281+37)
## Accuracy
(148+281)/(148+37+281+70)
```
# Question 3
```{r}
pred <- model %>% predict(test.data)
table(pred,test.data$Survived)
```
```{r}
## Sensitivity
54/(54+16)
## Specificity
90/(90+18)
## Accuracy
(54+90)/(54+16+90+18)
```
# Question 4
```{r}
# Plot MeanDecreaseAccuracy
varImpPlot(model$finalModel, type = 1)
# Plot MeanDecreaseGini
varImpPlot(model$finalModel, type = 2)
```
# Question 5
```{r}
varImp(model, type = 1)
##just for experimenting, I wanted to try based on meanDecreaseGini as well
varImp(model, type = 2)
```
# Question 6
The number of variables
```{r}
sqrt(36)
```